### ISSUE TITLE
Made change in Quiz_question activity UI and better improvement in dark theme and also made App Logo. let me know if you like it so  I make PR instantly.

### ISSUE THREAD

**Issue by siddhraj-sinh** [gdsc-pdeu/QuizApp#4]
App Logo:

![app_logo](https://user-images.githubusercontent.com/69664213/135867229-25d2ee1f-755d-4f9c-8f46-fc370374a06b.jpg)

Light Theme:

![Screenshot_20211004-192930_Quiz App](https://user-images.githubusercontent.com/69664213/135864926-ef9ded1b-4f6b-4e86-b16f-9847de4abee0.jpg)

Dark Theme:

![Screenshot_20211004-192901_Quiz App](https://user-images.githubusercontent.com/69664213/135865073-63bf6326-3418-44e1-b83a-f5aa4566416b.jpg)

**Comment by Miihir79** [comment]
Good changes made, liked the Logo. Go ahead make a PR.
